[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  command = "npm run dev --prefix frontend"
  port = 5173