[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"
  functions = "../backend/functions"

[functions]
  node_bundler = "esbuild"   # Best for modern JS
  external_node_modules = ["mongodb"]  # Ensure mongodb driver is bundled
  included_files = ["netlify/functions/**"]