[build]
  base = "frontend"
  command = "echo '{\"clientId\": \"${AUTH0_CLIENT_ID}\", \"domain\": \"${AUTH0_DOMAIN}\"}' > public/auth_config.json && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"